name: CI

on:

  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Clonacion de codigo
        uses: actions/checkout@v4
     
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '8'
          distribution: 'temurin'
      
      - name: Compilacion
        run: |
          mvn package
          #echo 'package'
#      - name: Analisis Sonar Cloud
#        run: |
#          mvn clean verify verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
#          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
#          -Dsonar.host.url=https://sonarcloud.io \
#          -Dsonar.organization=rvalenzuelamu \ 
#          -Dsonar.projectKey=rvalenzuelamu_ms-aumento-voto

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: 987219263
          password: ${{ secrets.DOCKER_PASS }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Docker build
        run: | 
          docker build -t 987219263/ms-aumento-voto:latest .

      - name: Docker push
        run: | 
          docker push 987219263/ms-aumento-voto:latest

